### ISSUE TITLE
DDP has a mistake,The code has a bug, the code reported such an error during training

### ISSUE THREAD

**Issue by wdc233** [LiheYoung/UniMatch#50]
`  File "/public/home/wdc/project/UniMatch/more-scenarios/remote-sensing/unimatch.py", line 39, in main
    rank, world_size = setup_distributed(port=args.port)
  File "/public/home/wdc/project/UniMatch/more-scenarios/remote-sensing/util/dist_helper.py", line 36, in setup_distributed
    dist.init_process_group(
  File "/public/home/wdc/anaconda3/envs/unimatch/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 627, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/public/home/wdc/anaconda3/envs/unimatch/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 255, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=8, worker_count=1, timeout=0:30:00)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 139953) of binary: /public/home/wdc/anaconda3/envs/unimatch/bin/python
Traceback (most recent call last):
  File "/public/home/wdc/anaconda3/envs/unimatch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/public/home/wdc/anaconda3/envs/unimatch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/public/home/wdc/anaconda3/envs/unimatch/lib/python3.10/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/public/home/wdc/anaconda3/envs/unimatch/lib/python3.10/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/public/home/wdc/anaconda3/envs/unimatch/lib/python3.10/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/public/home/wdc/anaconda3/envs/unimatch/lib/python3.10/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/public/home/wdc/anaconda3/envs/unimatch/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/public/home/wdc/anaconda3/envs/unimatch/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
unimatch.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-19_18:05:03
  host      : gpu1
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 139953)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================`

**Comment by LiheYoung** [comment]
I think you may need to check your environment.

**Comment by wdc233** [comment]
Thanks for the author's reply, but I built the environment exactly according to the requirements in the readme document, there is no difference, how to solve this problem

**Comment by wdc233** [comment]
Thanks for the author's reply, but I built the environment exactly according to the requirements in the readme document, there is no difference, how to solve this problem？
















在 2023-06-26 10:45:40，"Lihe Yang" ***@***.***> 写道：

Closed #50 as completed.
